site_name: TDEE App Documentation
nav:
  - Home: home.md
  - Nutrition: nutrition.md
  - Result: result.md
  - History: history.md
  - User:
    - Login: login.md
    - Register: register.md
    - Profile: profile.md
theme:
  name: readthedocs
